<?php
return [
    'adresa_dokumentace' => 'dokumentace',
    'dokumentace' => 'Dokumentace',
    'menu' => ['funkce' => 'Funkce', 'sablony' => 'Šablony', 'dokumentace' => 'Dokumentace', 'podporit' => 'Podpořit'],
    'stahnout' => 'Stáhnout',
    'preskocit' => 'Přeskočit na obsah',
    'hlavni_navigace' => 'Hlavní navigace',
    'menu_tlacitko' => 'Nabídka',
    'jazyk_webu' => 'Jazyk webu',
    'rezim' => 'Přepnout světlý a tmavý režim',
    'paticka_veta' => 'Redakční systém pro magazíny, noviny a blogy. Svobodný software pod licencí GNU GPL v2.',
    'paticka_projekt' => 'Projekt',
    'paticka_pomoc' => 'Pomoc',
    'paticka_odkazy' => [
        'projekt' => ['funkce' => 'Funkce', 'sablony' => 'Šablony', 'stahnout' => 'Stáhnout a nainstalovat', 'o-projektu' => 'O projektu'],
        'pomoc' => ['dokumentace' => 'Dokumentace', 'bezpecnost' => 'Bezpečnost', 'podporit' => 'Podpořit projekt', 'soukromi' => 'Ochrana soukromí'],
    ],
    'paticka_bez_sledovani' => 'Tento web nepoužívá cookies ani sledování.',
    'podpora_nadpis' => 'phpRS je zdarma a bez reklam',
    'podpora_text' => 'Vývoj, bezpečnostní opravy a tuhle dokumentaci platí dobrovolné příspěvky. Pomůže i malá pravidelná částka.',
    'podpora_tlacitko' => 'Podpořit na GitHub Sponsors',
    'podpora_jinak' => 'Jak jinak pomoci',
    'nenalezeno' => 'Stránka nenalezena',
    'nenalezeno_text' => 'Tahle adresa na webu není. Možná se stránka přesunula – zkuste úvod nebo hledání v dokumentaci.',
    'nenalezeno_domu' => 'Na úvodní stránku',
    'doc_hledat' => 'Hledat v dokumentaci',
    'doc_hledat_nic' => 'Nic nenalezeno.',
    'doc_obsah' => 'Na této stránce',
    'doc_predchozi' => 'Předchozí',
    'doc_dalsi' => 'Další',
    'doc_verze' => 'Platí pro verzi',
    'doc_kapitoly' => 'Kapitoly',
    'doc_prehled' => 'Přehled',
];
