<?php
return [
    'adresy' => ['funkce' => 'funktionen', 'sablony' => 'vorlagen', 'stahnout' => 'download', 'podporit' => 'unterstuetzen', 'bezpecnost' => 'sicherheit', 'o-projektu' => 'ueber-das-projekt', 'soukromi' => 'datenschutz'],
    'adresa_dokumentace' => 'dokumentation',
    'dokumentace' => 'Dokumentation',
    'menu' => ['funkce' => 'Funktionen', 'sablony' => 'Vorlagen', 'dokumentace' => 'Dokumentation', 'podporit' => 'Unterstützen'],
    'stahnout' => 'Download',
    'preskocit' => 'Zum Inhalt springen',
    'hlavni_navigace' => 'Hauptnavigation',
    'menu_tlacitko' => 'Menü',
    'jazyk_webu' => 'Sprache der Website',
    'rezim' => 'Zwischen hellem und dunklem Modus wechseln',
    'paticka_veta' => 'Redaktionssystem für Magazine, Zeitungen und Blogs. Freie Software unter der Lizenz GNU GPL v2.',
    'paticka_projekt' => 'Projekt',
    'paticka_pomoc' => 'Hilfe',
    'paticka_odkazy' => [
        'projekt' => ['funkce' => 'Funktionen', 'sablony' => 'Vorlagen', 'stahnout' => 'Herunterladen und installieren', 'o-projektu' => 'Über das Projekt'],
        'pomoc' => ['dokumentace' => 'Dokumentation', 'bezpecnost' => 'Sicherheit', 'podporit' => 'Projekt unterstützen', 'soukromi' => 'Datenschutz'],
    ],
    'paticka_bez_sledovani' => 'Diese Website verwendet weder Cookies noch Tracking.',
    'podpora_nadpis' => 'phpRS ist kostenlos und werbefrei',
    'podpora_text' => 'Entwicklung, Sicherheitskorrekturen und diese Dokumentation werden durch freiwillige Beiträge finanziert. Auch ein kleiner regelmäßiger Betrag hilft.',
    'podpora_tlacitko' => 'Auf GitHub Sponsors unterstützen',
    'podpora_jinak' => 'Andere Wege zu helfen',
    'nenalezeno' => 'Seite nicht gefunden',
    'nenalezeno_text' => 'Diese Adresse gibt es auf der Website nicht. Vielleicht wurde die Seite verschoben – versuchen Sie es mit der Startseite oder der Suche in der Dokumentation.',
    'nenalezeno_domu' => 'Zur Startseite',
    'doc_hledat' => 'In der Dokumentation suchen',
    'doc_hledat_nic' => 'Nichts gefunden.',
    'doc_obsah' => 'Auf dieser Seite',
    'doc_predchozi' => 'Zurück',
    'doc_dalsi' => 'Weiter',
    'doc_verze' => 'Gilt für Version',
    'doc_kapitoly' => 'Kapitel',
    'doc_prehled' => 'Übersicht',
];
