<?php
return [
    'adresy' => ['funkce' => 'features', 'sablony' => 'templates', 'stahnout' => 'download', 'podporit' => 'support', 'bezpecnost' => 'security', 'o-projektu' => 'about', 'soukromi' => 'privacy'],
    'adresa_dokumentace' => 'docs',
    'dokumentace' => 'Documentation',
    'menu' => ['funkce' => 'Features', 'sablony' => 'Templates', 'dokumentace' => 'Documentation', 'podporit' => 'Support'],
    'stahnout' => 'Download',
    'preskocit' => 'Skip to content',
    'hlavni_navigace' => 'Main navigation',
    'menu_tlacitko' => 'Menu',
    'jazyk_webu' => 'Site language',
    'rezim' => 'Switch between light and dark mode',
    'paticka_veta' => 'A content management system for magazines, newspapers and blogs. Free software under the GNU GPL v2 licence.',
    'paticka_projekt' => 'Project',
    'paticka_pomoc' => 'Help',
    'paticka_odkazy' => [
        'projekt' => ['funkce' => 'Features', 'sablony' => 'Templates', 'stahnout' => 'Download and install', 'o-projektu' => 'About the project'],
        'pomoc' => ['dokumentace' => 'Documentation', 'bezpecnost' => 'Security', 'podporit' => 'Support the project', 'soukromi' => 'Privacy'],
    ],
    'paticka_bez_sledovani' => 'This website uses no cookies and no tracking.',
    'podpora_nadpis' => 'phpRS is free and has no ads',
    'podpora_text' => 'Development, security fixes and this documentation are paid for by voluntary contributions. Even a small regular amount helps.',
    'podpora_tlacitko' => 'Support on GitHub Sponsors',
    'nenalezeno' => 'Page not found',
    'nenalezeno_text' => 'This address does not exist on the website. The page may have moved – try the home page or the documentation search.',
    'nenalezeno_domu' => 'Go to the home page',
    'doc_hledat' => 'Search the documentation',
    'doc_hledat_nic' => 'Nothing found.',
    'doc_obsah' => 'On this page',
    'doc_predchozi' => 'Previous',
    'doc_dalsi' => 'Next',
    'doc_verze' => 'Applies to version',
    'doc_kapitoly' => 'Chapters',
    'doc_prehled' => 'Overview',
];
